gridmaps:
    image: "selcolumbia/osm-gridmaps"
    links:
      - "db:db"
    volumes:
      - ./database.yml:/home/app/openstreetmap-website/config/database.yml
      - ./application.yml:/home/app/openstreetmap-website/config/application.yml
      - ./gridmaps-nginx.conf:/etc/nginx/sites-enabled/gridmaps-nginx.conf

db:
    image: "selcolumbia/osm-db"

dev:
    image: "selcolumbia/osm-gridmaps-dev"
    volumes:
      - ~/src/openstreetmap-website/:/src/openstreetmap-website
      - ./database.yml:/openstreetmap-website/config/database.yml
      - ./application.yml:/openstreetmap-website/config/application.yml
    links:
      - "db:db"
    ports:
      - "3000:3000"
